# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build - All Samples
on:
  push:
    #Change the branch name to <<main>>
    #Change the path to the folder where your code resides. Any change here will start the activity. 
    branches:
      - main
    paths:
      - '**'
  workflow_dispatch:
env:
    CI: false
jobs:

  build-python-samples:
    runs-on: windows-latest
    #Add project path, name and version as below for any new additions
    strategy:
      matrix:
        include:
            - project_path: 'samples/bot-conversation/python'
              name: 'bot-conversation'
              version: '3.7'
            - project_path: 'samples/bot-teams-authentication/python'
              name: 'bot-teams-authentication'
              version: '3.7'
            - project_path: 'samples/bot-file-upload/python'
              name: 'bot-file-upload'
              version: '3.7'
            - project_path: 'samples/bot-task-module/python'
              name: 'bot-task-module'
              version: '3.7'
            - project_path: 'samples/bot-initiate-thread-in-channel/python'
              name: 'bot-initiate-thread-in-channel'
              version: '3.7'
            - project_path: 'samples/msgext-search/python'
              name: 'msgext-search'
              version: '3.7'
            - project_path: 'samples/msgext-action/python'
              name: 'msgext-action'
              version: '3.7'
            - project_path: 'samples/msgext-action-preview/python'
              name: 'msgext-action-preview'
              version: '3.7'
            - project_path: 'samples/msgext-link-unfurling/python'
              name: 'msgext-link-unfurling'
              version: '3.7'
            - project_path: 'samples/msgext-search-auth-config/python'
              name: 'msgext-search-auth-config'
              version: '3.7'

      fail-fast: false
    name: Build all "${{ matrix.name }}" python
    defaults:
      run:
        working-directory: "${{ matrix.project_path }}"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.version }}"
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt